name: SkyFeederFieldUtility
options:
  minimumXcodeGenVersion: 2.37.0
  deploymentTarget:
    iOS: "16.0"

configs:
  Debug: debug
  Release: release

packages:
  SkyFeederUI:
    path: ./SkyFeederUI

targets:
  SkyFeederFieldUtility:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    configFiles:
      Debug: SkyFeederFieldUtility/Support/Configurations/AppConfig.xcconfig
      Release: SkyFeederFieldUtility/Support/Configurations/AppConfig.xcconfig
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: ""
        PRODUCT_BUNDLE_IDENTIFIER: $(APP_BUNDLE_IDENTIFIER)
        DEVELOPMENT_TEAM: $(APP_DEVELOPMENT_TEAM)
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: 3
    sources:
      - path: SkyFeederFieldUtility/App
      - path: SkyFeederFieldUtility/Models
      - path: SkyFeederFieldUtility/Providers
      - path: SkyFeederFieldUtility/Support
        excludes:
          - Configurations/**
          - Info.plist
      - path: SkyFeederFieldUtility/ViewModels
      - path: SkyFeederFieldUtility/Views
    resources:
      - path: SkyFeederFieldUtility/Resources

















    info:
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: SkyFeeder
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: SkyFeeder
        CFBundleIconName: AppIcon
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon
            UIPrerenderedIcon: false
        CFBundleIcons~ipad:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon
            UIPrerenderedIcon: false
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen:
          UIColorName: ''
          UIImageName: ''
        UIRequiredDeviceCapabilities:
          - arm64
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSExceptionDomains:
            10.0.0.4:
              NSIncludesSubdomains: false
              NSTemporaryExceptionAllowsInsecureHTTPLoads: true
        NSPhotoLibraryAddUsageDescription: "Needed to save captures to Photos."
        NSPhotoLibraryUsageDescription: "Needed to access your Photos."
        SKAllowLocalHttp: true
        SKDefaultProvider: "PresignedHTTP"
    preBuildScripts:
      - name: Validate Info.plist bundle keys
        script: |
          set -euo pipefail
          : "${SRCROOT:?SRCROOT is not set}"
          PLIST_PATH="${INFOPLIST_FILE:-}"
          if [[ -n "${PLIST_PATH}" && "${PLIST_PATH}" != /* ]]; then
            PLIST_PATH="${SRCROOT}/${PLIST_PATH}"
          fi
          if [[ -z "${PLIST_PATH}" || ! -f "${PLIST_PATH}" ]]; then
            FALLBACK="${TARGET_BUILD_DIR:-}/${INFOPLIST_PATH:-}"
            if [[ -n "${FALLBACK}" && -f "${FALLBACK}" ]]; then
              PLIST_PATH="${FALLBACK}"
            else
              echo "::warning::Info.plist not found (looked for '${PLIST_PATH}' and '${FALLBACK}'). Skipping validation."
              exit 0
            fi
          fi
          echo "Validating Info.plist at ${PLIST_PATH}"
          missing=0
          for KEY in CFBundleIconName UILaunchScreen UISupportedInterfaceOrientations~ipad; do
            if /usr/libexec/PlistBuddy -c "Print :${KEY}" "${PLIST_PATH}" >/dev/null 2>&1; then
              echo "✓ ${KEY} present"
            else
              echo "::warning::Info.plist missing ${KEY}"
              missing=1
            fi
          done
          if [[ "${missing}" -ne 0 ]]; then
            echo "::warning::One or more Info.plist keys missing. Build will continue."
          fi
          exit 0
    dependencies:
      - package: SkyFeederUI

