name: SkyFeederFieldUtility
options:
  minimumXcodeGenVersion: 2.37.0
  deploymentTarget:
    iOS: "16.0"

configs:
  Debug: debug
  Release: release

packages:
  SkyFeederUI:
    path: ./SkyFeederUI

targets:
  SkyFeederFieldUtility:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    configFiles:
      Debug: SkyFeederFieldUtility/Support/Configurations/AppConfig.xcconfig
      Release: SkyFeederFieldUtility/Support/Configurations/AppConfig.xcconfig
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: ""
        PRODUCT_BUNDLE_IDENTIFIER: $(APP_BUNDLE_IDENTIFIER)
        DEVELOPMENT_TEAM: $(APP_DEVELOPMENT_TEAM)
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: 3
    sources:
      - path: SkyFeederFieldUtility/App
      - path: SkyFeederFieldUtility/Models
      - path: SkyFeederFieldUtility/Providers
      - path: SkyFeederFieldUtility/Support
        excludes:
          - Configurations/**
          - Info.plist
      - path: SkyFeederFieldUtility/ViewModels
      - path: SkyFeederFieldUtility/Views
    resources:
      - path: SkyFeederFieldUtility/Resources

















    info:
      path: SkyFeederFieldUtility/Support/Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleDisplayName: SkyFeeder
        CFBundleName: SkyFeeder
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIconName: AppIcon
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon
            UIPrerenderedIcon: false
        CFBundleIcons~ipad:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon
            UIPrerenderedIcon: false
        UILaunchScreen:
          UIColorName: ''
          UIImageName: ''
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    preBuildScripts:
      - name: Validate Info.plist bundle keys
        script: |
          set -euo pipefail
          PLIST="${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
          echo "Validating Info.plist at ${PLIST}"
          [[ -f "${PLIST}" ]] || { echo "Info.plist missing at ${PLIST}"; exit 1; }
          for KEY in CFBundleIconName UILaunchScreen UISupportedInterfaceOrientations~ipad; do
            if ! /usr/libexec/PlistBuddy -c "Print :${KEY}" "${PLIST}" >/dev/null 2>&1; then
              echo "Required Info.plist key ${KEY} missing"
              exit 1
            fi
            echo "✓ ${KEY} present"
          done
   dependencies:
      - package: SkyFeederUI
