name: SkyFeederFieldUtility
options:
  minimumXcodeGenVersion: 2.37.0
  deploymentTarget:
    iOS: "16.0"

configs:
  Debug: debug
  Release: release

packages:
  SkyFeederUI:
    path: ./SkyFeederUI

targets:
  SkyFeederFieldUtility:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    configFiles:
      Debug: SkyFeederFieldUtility/Support/Configurations/AppConfig.xcconfig
      Release: SkyFeederFieldUtility/Support/Configurations/AppConfig.xcconfig
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: SkyFeederFieldUtility/Support/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: $(APP_BUNDLE_IDENTIFIER)
        DEVELOPMENT_TEAM: $(APP_DEVELOPMENT_TEAM)
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
    sources:
      - path: SkyFeederFieldUtility/App
      - path: SkyFeederFieldUtility/Models
      - path: SkyFeederFieldUtility/Providers
      - path: SkyFeederFieldUtility/Support
        excludes:
          - Configurations/**
          - Info.plist
      - path: SkyFeederFieldUtility/ViewModels
      - path: SkyFeederFieldUtility/Views
    resources:
      - path: SkyFeederFieldUtility/Resources/Assets.xcassets
      - path: SkyFeederFieldUtility/Resources
        excludes:
          - Assets.xcassets/**
    info:
      path: SkyFeederFieldUtility/Support/Info.plist
    dependencies:
      - package: SkyFeederUI

  SkyFeederFieldUtilityTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: SkyFeederFieldUtility/Tests
    dependencies:
      - target: SkyFeederFieldUtility
