#pragma once
#define TOPIC_STATUS                 "skyfeeder/" DEVICE_ID "/status"
#define TOPIC_ACK                    "skyfeeder/" DEVICE_ID "/ack"
#define TOPIC_TELEMETRY              "skyfeeder/" DEVICE_ID "/telemetry"
#define TOPIC_CMD_ANY                "skyfeeder/" DEVICE_ID "/cmd/#"
#define TOPIC_CMD_LED                "skyfeeder/" DEVICE_ID "/cmd/led"
#define TOPIC_CMD_CALIBRATE          "skyfeeder/" DEVICE_ID "/cmd/calibrate"
#define TOPIC_CMD_CAMERA             "skyfeeder/" DEVICE_ID "/cmd/camera"
#define TOPIC_EVENT_VISIT            "skyfeeder/" DEVICE_ID "/event/visit"
#define TOPIC_EVENT_CAMERA_SNAPSHOT  "skyfeeder/" DEVICE_ID "/event/camera/snapshot"
